"""Initial migration

Revision ID: 0187e4d4f98c
Revises: 
Create Date: 2025-12-26 01:16:36.210337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0187e4d4f98c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_tokens', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_device_tokens_is_admin'), 'device_tokens', ['is_admin'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_device_tokens_is_admin'), table_name='device_tokens')
    op.drop_column('device_tokens', 'is_admin')
    # ### end Alembic commands ###
