"""Initial migration

Revision ID: 0187e4d4f98c
Revises: 
Create Date: 2025-12-26 01:16:36.210337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0187e4d4f98c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if device_tokens table exists, if not create it
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'device_tokens' not in tables:
        # Create the device_tokens table with all columns
        op.create_table(
            'device_tokens',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('device_id', sa.String(length=255), nullable=False),
            sa.Column('fcm_token', sa.String(length=500), nullable=False),
            sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='false'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
        op.create_index(op.f('ix_device_tokens_device_id'), 'device_tokens', ['device_id'], unique=False)
        op.create_index(op.f('ix_device_tokens_fcm_token'), 'device_tokens', ['fcm_token'], unique=True)
        op.create_index(op.f('ix_device_tokens_is_admin'), 'device_tokens', ['is_admin'], unique=False)
    else:
        # Table exists, check if is_admin column exists
        columns = [col['name'] for col in inspector.get_columns('device_tokens')]
        if 'is_admin' not in columns:
            op.add_column('device_tokens', sa.Column('is_admin', sa.Boolean(), nullable=True))
            op.create_index(op.f('ix_device_tokens_is_admin'), 'device_tokens', ['is_admin'], unique=False)
    
    # Check if products table exists before creating index
    if 'products' in tables:
        try:
            op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
        except Exception:
            pass  # Index might already exist or table structure issue
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if products table exists before trying to drop index
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'products' in tables:
        try:
            op.drop_index(op.f('ix_products_id'), table_name='products')
        except Exception:
            pass  # Index might not exist
    
    # Check if device_tokens table exists before trying to drop column/index
    if 'device_tokens' in tables:
        columns = [col['name'] for col in inspector.get_columns('device_tokens')]
        if 'is_admin' in columns:
            try:
                op.drop_index(op.f('ix_device_tokens_is_admin'), table_name='device_tokens')
            except Exception:
                pass  # Index might not exist
            op.drop_column('device_tokens', 'is_admin')
    # ### end Alembic commands ###
