"""add_is_active_to_product

Revision ID: 361246192298
Revises: 0187e4d4f98c
Create Date: 2026-02-02 12:43:46.087605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361246192298'
down_revision: Union[str, None] = '0187e4d4f98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_tokens_fcm_token', table_name='device_tokens')
    op.create_unique_constraint(None, 'device_tokens', ['fcm_token'])
    op.drop_column('orders', 'payment_proof_file_id')
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('products', 'image_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('products', 'is_active')
    op.add_column('orders', sa.Column('payment_proof_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device_tokens', type_='unique')
    op.create_index('ix_device_tokens_fcm_token', 'device_tokens', ['fcm_token'], unique=True)
    # ### end Alembic commands ###
